
-

  hosts: all
  user: docker
  become: True

  tasks:
    - name: Run bash script to servers
      command: sh /var/tmp/os_version.sh
      register: ps

    # Print the shell task's stdout.
    - debug: msg={{ ps.stdout }}


...